services:
  openvpn-client:
    image: ghcr.io/dyson-spherical/openvpn-client:latest
    container_name: openvpn-client
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - ALLOWED_SUBNETS=10.0.0.0/24,192.168.100.0/24,192.168.10.0/24
    volumes:
      - ./local:/config
    restart: unless-stopped
